channels:
- conda-forge
dependencies:
# Jupyter
- widgetsnbextension
# Python Kernel
- ipykernel
- ipywidgets
- altair=3.1
- bqplot=0.11.6
- dask=2.1
- matplotlib
- pandas
- python=3.7
- scikit-image
- scikit-learn
- seaborn
- tensorflow
- sympy
- pyyaml
- traittypes
- invoke=1.2
# R Kernel
- r-ggplot2
- r-irkernel
